settings:
  all_files: &all_files !settings
    included:
      - ~+/bellybutton/*
    excluded:
      - ~+/.tox/*
    allow_ignore: yes

  tests_only: &tests_only !settings
    included:
      - ~+/tests/*
    excluded:
      - ~+/.tox/*
    allow_ignore: yes

  excluding_tests: &excluding_tests !settings
    included:
      - ~+/bellybutton/*
    excluded:
      - ~+/tests/*
      - ~+/.tox/*
    allow_ignore: yes

  excluding_cli: &excluding_cli !settings
    <<: *excluding_tests
    excluded:
      - ~+/tests/*
      - ~+/.tox/*
      - ~+/bellybutton/cli.py

default_settings: *excluding_tests

rules:
  IllicitPrint:
    description: Use of print outside the CLI module is disallowed.
    expr: //Print | //Call[func/Name[@id='print' or @id='pprint']]
    example: |
      print(x)
    settings: *excluding_cli

  IllicitOpen:
    description: Performing I/O outside the CLI module is disallowed.
    expr: //Call[func/Name/@id='open']
    example: |
      with open('x') as f:
        pass
    settings: *excluding_cli
